# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/grpc.proto\x12\tinference\x1a\x1cgoogle/protobuf/struct.proto\"5\n\tMLRequest\x12(\n\x07request\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"7\n\nMLResponse\x12)\n\x08response\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2>\n\x02ML\x12\x38\n\x07Predict\x12\x14.inference.MLRequest\x1a\x15.inference.MLResponse\"\x00\x42\tZ\x07./fmprob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./fmpro'
  _MLREQUEST._serialized_start=61
  _MLREQUEST._serialized_end=114
  _MLRESPONSE._serialized_start=116
  _MLRESPONSE._serialized_end=171
  _ML._serialized_start=173
  _ML._serialized_end=235
# @@protoc_insertion_point(module_scope)
